---
services:
  db:
    image: poornapj/library:dbservice
    deploy:
      replicas: 1
    ports:
      - "3306:3306"


  auth_service:
    image: poornapj/library:authservice
    deploy:
      replicas: 1
    ports:
      - "5001:5001"
    depends_on:
      - db


  book_service:
    image: poornapj/library:bookservice
    deploy:
      replicas: 1
    ports:
      - "5002:5002"
    depends_on:
      - db

  borrow_service:
    image: poornapj/library:borrowservice
    deploy:
      replicas: 1
    ports:
      - "5003:5003"
    depends_on:
      - db


  frontend:
    image: poornapj/library:frontendservice
    deploy:
      replicas: 1
    ports:
      - "5000:5000"
  
    depends_on:
      - auth_service
      - book_service
      - borrow_service
                          
