---
services:
  db:
    image: poornapj/library2:database
    deploy:
      replicas: 1
    ports:
      - "3306:3306"


  auth_service:
    image: poornapj/library2:authentication
    deploy:
      replicas: 1
    ports:
      - "5001:5001"
    depends_on:
      - db


  book_service:
    image: poornapj/library2:books
    deploy:
      replicas: 1
    ports:
      - "5002:5002"
    depends_on:
      - db

  borrow_service:
    image: poornapj/library2:borrowbooks
    deploy:
      replicas: 1
    ports:
      - "5003:5003"
    depends_on:
      - db


  frontend:
    image: poornapj/library2:application
    deploy:
      replicas: 1
    ports:
      - "5000:5000"
  
    depends_on:
      - auth_service
      - book_service
      - borrow_service
                          
